#!/bin/sh

ftest="$1"

echo "Test : ${ftest}"

Line=`grep "TARGET = " makefile`
NewLine="TARGET = test_$ftest"
sed -i "s#${Line}#${NewLine}#g" makefile

Line=`grep "TARGET = " makefile`
echo "$Line"


make 
./test_${ftest} -f ../config/cce_${ftest}.json

