#!/bin/sh

unit="G"
VariableName="B0"
varOpt="0 100 200 300 400 500 600 700 800 900 1000 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521 522 523 524 525"

node=3
qos=9

vsrcjob="{Nstate}_VariableArray_idm3"

#############################################
# Run jobs for variables
#############################################
if [[ "${vsrcjob}" == *"_VariableArray"* ]];then 

    echo ""
    echo "  Run job version : ${vsrcjob}"

    varOptArray=(${varOpt})
    nVarOptArray=${#varOptArray[@]}

    varOptSta=0
    varOptEnd=$(( ${nVarOptArray} - 1 ))

    cd ./${VariableName}/
    
        QosChanger job $node $qos "off"
        sbatch --array=${varOptSta}-${varOptEnd} job

        for (( i=${varOptSta}; i<=${varOptEnd}; i++))
        do
            echo "  ${VariableName} = ${varOptArray[i]}"
        done        
    cd ..

    echo ""
fi
#############################################
# Run jobs for the number of configurations 
#############################################
if [[ "${vsrcjob}" == *"_ConfigArray"* ]];then 

    echo ""
    echo "   Run job version : ${vsrcjob}"

    for var in ${varOpt} 
    do
        cd ./${VariableName}/${var}${unit}
        
        #############################################
        # Make array 
        #############################################
        ArrayValues=""
    
        for (( i=1; i<1; i=(( ${i} + 1 )) ))
        do
            if [ "${i}" == "1" ];then
                ArrayValues+="${i}"
            else
                ArrayValues+=",${i}"
            fi
        done
        #############################################
    
        QosChanger job $node $qos "off"
        sbatch --array=${ArrayValues} job
    
        cd ../../
    
        echo "   ${VariableName} = ${var}"
    done

    echo ""
fi
#############################################
