#!/bin/sh

unit="G"
VariableName="B0"
varOpt="0 100 200 300 400 500 600 700 800 900 1000 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521 522 523 524 525"

tolerance=
which="sE"
##############################################################
configs="$(seq 1 1 1)"
states="$(seq 1 1 1)"

ConvTestCode="/home/huijin/scrp/pyFunction/22.ConvTest/do_convTest.py"

ECDir="./summary/${VariableName}/ErrorCorr/"
tEDir="./summary/${VariableName}/TimeEnsemble/"
sEDir="./summary/${VariableName}/SpatialEnsemble/"
##############################################################
for c in ${configs} 
do
    ##################################################################################
    # Error Correction
    if [ $which == "EC" ]; then
    for s in ${states}
    do
        ECdataList=""
        for var in ${varOpt} 
        do
            ECdatahead="gCCE2_DiaP1_10ppm_${VariableName}_${var}${unit}_EC_"
            ECouthead="gCCE2_DiaP1_10ppm_${VariableName}_EC_"
            ECdata="${ECDir}${ECdatahead}${c}{${s}}"
            ECdataList+=" ${ECdata}"
        done
        ECout="${ECDir}${ECouthead}${c}{${s}}"
        ${ConvTestCode} "${ECdataList}" "${varOpt}" "${VariableName}" "${unit}" "${tolerance}" "${ECout}"
    done
    fi
    ##################################################################################
    ##################################################################################
    # Time Ensemble
    if [ $which == "tE" ]; then
    tEdataList=""
    for var in ${varOpt} 
    do
        tEdatahead="gCCE2_DiaP1_10ppm_${VariableName}_${var}${unit}_tE_"
        tEdatatail="{1T1}_conv1"
        tEouthead="gCCE2_DiaP1_10ppm_${VariableName}_tE_"
        tEdata="${tEDir}${tEdatahead}${c}${tEdatatail}"
        tEdataList+=" ${tEdata}"
    done
    tEout="${tEDir}${tEouthead}${c}${tEdatatail}"
    ${ConvTestCode} "${tEdataList}" "${varOpt}" "${VariableName}" "${unit}" "${tolerance}" "${tEout}"
    fi
    #################################################################################
done

####################################################################################
# Spatial Ensemble
if [ $which == "sE" ]; then
sEdataList=""
for var in ${varOpt} 
do
    sEdatahead="gCCE2_DiaP1_10ppm_${VariableName}_${var}${unit}_sE_"
    sEdatatail="conv1x1"
    sEouthead="gCCE2_DiaP1_10ppm_${VariableName}_sE_"
    sEdata="${sEDir}${sEdatahead}${sEdatatail}"
    sEdataList+=" ${sEdata}"
done
sEout="${sEDir}${sEouthead}${sEdatatail}"
${ConvTestCode} "${sEdataList}" "${varOpt}" "${VariableName}" "${unit}" "${tolerance}" "${sEout}" > out
fi
###################################################################################

