#!/bin/sh

unit="G"
VariableName="B0"
varOpt="0 100 200 300 400 500 600 700 800 900 1000 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521 522 523 524 525"

##############################################################
configs="$(seq 1 1 1)"
states="$(seq 1 1 1)"

fittingCode="/home/huijin/git/CoherenceAnalyzer/run.py"

CdMkDir ./summary/
CdMkDir ./summary/${VariableName}/
CdMkDir ./summary/${VariableName}/ErrorCorr
CdMkDir ./summary/${VariableName}/TimeEnsemble
CdMkDir ./summary/${VariableName}/SpatialEnsemble
###############################################################
#for var in ${varOpt} 
#do
#    
#    datadirectory="./${VariableName}/${var}${unit}"
#    rawdatadirectory="${datadirectory}/rawdata"
#    rawdatahead="gCCE2_DiaP1_10ppm_${VariableName}_${var}${unit}"
#
#    ###################################################
#    # Convert Name
#	variable_name_1="CONF"
#	variable_values_1="${configs}"
#	variable_name_2="STATE"
#	variable_values_2="${states}"
#
#	data_directory="./${VariableName}/${var}${unit}/rawdata/"
#	data_filename_format="${rawdatahead}_${variable_name_1}_state${variable_name_2}_wiDiv"
#	data_filename_format_ref="${rawdatahead}_${variable_name_1}_state${variable_name_2}_noDiv"
#
#	result_directory="./summary/${VariableName}/SpatialEnsemble/"
#	result="${result_directory}${rawdatahead}_sE"
#
#	# Ensemble average option   : -ea
#	# Unit conversion           : -uc [unit] (use default unit (ms))
#	# Nan to num                : -ntn
#	# Error correction			: -err
#	python ~/git/CoherenceAnalyzer/run.py -d "${data_directory}" -fi "${data_filename_format}" -vn ${variable_name_1} ${variable_name_2} -v ${variable_values_1} -v ${variable_values_2} -uc "ms" -ea -ntn -fo "${result}" -pl -fit -err_d "${data_directory}" -err_fi "${data_filename_format_ref}" -err
#
#done

	variable_name="BFIELD"
	result_directory="./summary/${VariableName}/SpatialEnsemble/"

    rawdatahead="gCCE2_DiaP1_10ppm_${VariableName}_${variable_name}${unit}"
	result_filename="${rawdatahead}_sE_conv1"

	python ~/git/CoherenceAnalyzer/run.py -d "${result_directory}" -fi "${result_filename}" -vn ${variable_name} -v ${varOpt} -uc "us" -ntn -fo "${result_directory}${result_filename}" -pl_i 
	python ~/git/CoherenceAnalyzer/run.py -d "${result_directory}" -fi "${result_filename}" -vn ${variable_name} -v ${varOpt} -uc "us" -ntn -fo "${result_directory}${result_filename}" -pl_i -fit_w -pl_T -pl_p
