#!/bin/sh

PwdDir="`pwd`"

cd ../../../

    make

cd "${PwdDir}" 

code="../../../bin/main.out"
ccein="./cce.json"

process=24

mpirun -n ${process} ${code} -f ${ccein} -I "./../CCE_Reprod/Bath_Data/1.single_data/bath_DiaP1_1ppm_1" -N 2 > process
