#!/bin/sh
Method="CCE"

Directory="/home/huijin/tutorial/Diamond_NV_P1Bath/bath"

DefectFile="${Directory}/14N_10ppm/bath_DiaP1_10ppm_Defect"
BathFile="${Directory}/14N_10ppm/bath_DiaP1_10ppm_"
GyroFile="${Directory}/DiaP1_gyro"
AvaaxFile="Random"
StateFile="Random"
ExStateFile="Random"
CCEinFile="${Directory}/DiaFullP1_14N_exp.json"

## Variables ##
rBathOpt="370"
rDipOpt="330"
B0Opt="500"
OrderOpt="2"
NkOpt=""

## Fixed parameters ## 
OrderFix="2"
PulseFix="1"
deltaTFix="0.0005"
nStepFix="300"

B0Fix="500"
rBathFix="370"
rDipFix="330"
rDsrdrFix=""
alphaFix="-1"
betaFix="0"

# clustering algo
ClusAlgo="0"
addClus="0"
NkFix="[0,0,0]"

# Hamiltonian
HFOpt=0
HFFile=0 
HFCutoff=0
QuadOpt=0

# JOB
JOBNAME="CCE2e2n_DiaP1_10ppm_"
OutFileDir="./rawdata/"
OutFileHead="CCE2e2n_DiaP1_10ppm_"
OutFileTail=""

