#!/bin/sh

source ${src} 

cat << EOF > "${WorkingSubDir}/job"
#!/bin/sh
#SBATCH -J ${JOBNAME}${VariableName}
#SBATCH -p 24core
#SBATCH --nodes=8
#SBATCH --ntasks-per-node=24
#SBATCH --cpus-per-task=1
#SBATCH --out outfile
#SBATCH --time=48:00:00
#SBATCH --qos=medium
#SBATCH --mem-per-cpu=5300

module purge 
module load icc18 icc18.impi fftw mkl2018 
export LD_LIBRARY_PATH=/home/CQML/lib/gsl-2.7.1/lib:\$LD_LIBRARY_PATH

export OMP_NUM_THREADS=\$SLURM_CPUS_PER_TASK
NTASKS=\$((\$SLURM_NTASKS_PER_NODE * \$SLURM_JOB_NUM_NODES))

echo "NTASKS =" \$NTASKS
echo "NUM_NODES = " \$SLURM_JOB_NUM_NODES
env | grep SLURM

node_process=\$NTASKS

#############################################
# VariableName

varOpt=( ${varOpt} )

s="\$SLURM_ARRAY_TASK_ID"
varDir="\${varOpt[s]}${unit}"

cd \${varDir}

#############################################
# Main Paramaters

#bath number

configures="\$(seq -s ' ' ${cista} 1 ${ciend})"
states="\$(seq -s ' ' ${sista} 1 ${siend})"

#option input
CodePath="${CodePath}"

# inputfiles
mkdir "${OutFileDir}"
option_input="./ccein.js"
BathFile="${BathFile}"
AvaaxFile="${AvaaxFile}"
StateFile="${StateFile}"
ExStateFile="${ExStateFile}"

# outfiles
outFile="${OutFileDir}${OutFileHead}${VariableName}${OutFileTail}_\${varDir}_"

#time checking
startTime=\$(date +%s.%N)
startTime_string=\`date\`
#############################################################################
#about CCE2 calculation 

for m in \$configures
do
	for s in \$states
	do

   	 mpirun -n \${node_process} \${CodePath} -f \${option_input} -I "\${BathFile}\${m}" -a "\${AvaaxFile}\${m}" -s "\${StateFile}\${s}" -S "\${ExStateFile}\${s}" -N 1 -o "\${outFile}\${m}{\${s}}" > "Process_\${m}{\${s}}"

	done
done

#############################################################################$
endTime=\$(date +%s.%N)
endTime_string=\`date\`

elapsed=\`echo "(\$endTime-\$startTime)" |bc\`
htime=\`echo "\$elapsed/3600"|bc\`
mtime=\`echo "(\$elapsed/60)-(\$htime*60)"|bc\`
stime=\`echo "\$elapsed-((\$elapsed/60)*60)"|bc\`
echo "Start time : \$startTime_string"
echo "End time   : \$endTime_string"
echo "Total time : \${htime}H \${mtime}M \${stime}S"
#############################################

cd ..

EOF

