#!/bin/sh

source ${src} 

cat << EOF > "${WorkingSubDir}/job"
#!/bin/sh
#SBATCH -J ${JOBNAME}${VariableName}
#SBATCH -p 64core
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=64
#SBATCH --cpus-per-task=1
#SBATCH --out outfile
#SBATCH --time=2-00:00:00
#SBATCH --qos=small-2
#SBATCH --mem-per-cpu=0

module purge 
module load  intel-23.2/icc-23.2  intel-23.2/gsl-2.8  intel-23.2/eigen-3.4.0

NTASKS=\$((\$SLURM_NTASKS_PER_NODE * \$SLURM_JOB_NUM_NODES))

echo "NTASKS =" \$NTASKS
echo "NUM_NODES = " \$SLURM_JOB_NUM_NODES
env | grep SLURM

node_process=\$NTASKS

#############################################
# VariableName

varOpt=( ${varOpt} )

s="\$SLURM_ARRAY_TASK_ID"
varDir="\${varOpt[s]}${unit}"

cd \${varDir}

#############################################
# Main Paramaters

#bath number
cista="${cista}"
ciend="${ciend}"

sista="${sista}"
siend="${siend}"

configures="\$(seq -s ' ' \${cista} 1 \${ciend})"
states="\$(seq -s ' ' \${sista} 1 \${siend})"

Nstate=\$(( \${siend} - \${sista} + 1 ))

#option input
CodePath="${CodePath}"

# inputfiles
mkdir "${OutFileDir}"
option_input="./ccein.js"
BathFile="${BathFile}"
AvaaxFile="${AvaaxFile}"
StateFile="${StateFile}"
ExStateFile="${ExStateFile}"

# outfiles
outFile="${OutFileDir}${OutFileHead}${VariableName}${OutFileTail}_\${varDir}_"

#time checking
startTime=\$(date +%s.%N)
startTime_string=\`date\`
#############################################################################
#about CCE2 calculation 

for m in \$configures
do
   	 mpirun -n \${node_process} \${CodePath} -f \${option_input} -I "\${BathFile}\${m}" -a "\${AvaaxFile}\${m}" -s "\${StateFile}" -S "\${ExStateFile}" -o "\${outFile}\${m}" -N "\$Nstate" > "Process_\${m}"

done


#############################################################################$
endTime=\$(date +%s.%N)
endTime_string=\`date\`

elapsed=\`echo "(\$endTime-\$startTime)" |bc\`
htime=\`echo "\$elapsed/3600"|bc\`
mtime=\`echo "(\$elapsed/60)-(\$htime*60)"|bc\`
stime=\`echo "\$elapsed-((\$elapsed/60)*60)"|bc\`
echo "Start time : \$startTime_string"
echo "End time   : \$endTime_string"
echo "Total time : \${htime}H \${mtime}M \${stime}S"
#############################################

cd ..

EOF

