#!/bin/sh

if [ "$#" -eq 1 ]; then
    message=$1 
else
    echo "Error!!"
    echo "For conduct \"commit\", message should be provided"
    exit
fi

make clean

git checkout -b "main"
wait
git add .
wait
git status
wait
git commit -m " $message"
wait
git push origin "main"
wait

