#!/bin/sh
#SBATCH -J gCCE2_DiaP1_10ppm_B0
#SBATCH -p 24core
#SBATCH --nodes=8
#SBATCH --ntasks-per-node=24
#SBATCH --cpus-per-task=1
#SBATCH --out outfile
#SBATCH --time=48:00:00
#SBATCH --qos=medium
#SBATCH --mem-per-cpu=5300

module purge 
module load 22.2/icc-22.2 22.2/fftw-3.3.10 22.2/gsl-2.7.1 

node_process=24

#############################################
# VariableName

varOpt=( 0 100 200 300 400 500 600 700 800 900 1000 505 506 507 508 509 510 511 512 513 514 515 516 517 518 519 520 521 522 523 524 525 )

for (( s=0; s<${#varOpt[@]}; s++))
do
varDir="${varOpt[s]}G"

cd ${varDir}

echo `pwd`
#############################################
# Main Paramaters

#bath number
cista="1"
ciend="1"

sista="1"
siend="1"

configures="$(seq -s ' ' ${cista} 1 ${ciend})"
states="$(seq -s ' ' ${sista} 1 ${siend})"

Nstate=$(( ${siend} - ${sista} + 1 ))

#option input
CodePath="/home/huijin/git/CCEX/bin/main.out"

# inputfiles
mkdir "./rawdata/"
option_input="./ccein.json"
BathFile="/home/huijin/tutorial/Diamond_NV_P1Bath/bath/14N_10ppm/bath_DiaP1_10ppm_"
AvaaxFile="Random"
StateFile="Random"
ExStateFile="Random"

# outfiles
outFile="./rawdata/gCCE2_DiaP1_10ppm_B0_${varDir}_"

#time checking
startTime=$(date +%s.%N)
startTime_string=`date`
#############################################################################
#about CCE2 calculation 

for m in $configures
do
   	 mpirun -n ${node_process} ${CodePath} -f ${option_input} -I "${BathFile}${m}" -a "${AvaaxFile}${m}" -s "${StateFile}" -S "${ExStateFile}" -o "${outFile}${m}" -N "$Nstate" > "Process_${m}"

done


#############################################################################$
endTime=$(date +%s.%N)
endTime_string=`date`

elapsed=`echo "($endTime-$startTime)" |bc`
htime=`echo "$elapsed/3600"|bc`
mtime=`echo "($elapsed/60)-($htime*60)"|bc`
stime=`echo "$elapsed-(($elapsed/60)*60)"|bc`
echo "Start time : $startTime_string"
echo "End time   : $endTime_string"
echo "Total time : ${htime}H ${mtime}M ${stime}S"
#############################################

cd ..
done
