#!/bin/sh

cd ../../../

    make

cd ./example/code_verification/1.1.ElectronSpinBath/

code="../../../bin/main.out"
ccein="./cce.json"

process=24

mpirun -np ${process} ${code} -f ${ccein} > process
