#!/bin/sh
Method="CCE"

Directory="$(git rev-parse --show-toplevel)/example/Diamond_NV_VpBath/bath"

DefectFile="${Directory}/50ppm/bath_DiaVp_50ppm_Defect"
BathFile="${Directory}/50ppm/bath_DiaVp_50ppm_"
GyroFile="${Directory}/DiaVp_gyro"
AvaaxFile="Random"
StateFile="Random"
ExStateFile="Random"
CCEinFile="${Directory}/"

## Variables ##
rBathOpt="240"
rDipOpt="220"
B0Opt="500"
OrderOpt="2"
NkOpt=""

## Fixed parameters ## 
OrderFix="2"
PulseFix="1"
deltaTFix="0.0002"
nStepFix="300"

B0Fix="500"
rBathFix="240"
rDipFix="220"
alphaFix="-1"
betaFix="0"

# clustering algo
ClusAlgo="0"
addClus="0"
NkFix="[0,0,0]"

# Hamiltonian
HFOpt=0
HFFile=0 
HFCutoff=0
QuadOpt=0

# JOB
JOBNAME="CCE2_DiaVp_50ppm_"
OutFileDir="./rawdata/"
OutFileHead="CCE2_DiaVp_50ppm_"
OutFileTail=""

