#!/bin/sh
Method="CCE"

Directory="/home/huijin/cal/bath/5.DiaExspins/P1"

DefectFile="${Directory}/P1bath_10ppm/bath_DiaP1_10ppm_Defect"
BathFile="${Directory}/P1bath_10ppm/bath_DiaP1_10ppm_"
GyroFile="${Directory}/P1_gyro"
AvaaxFile="Random"
StateFile="Random"
ExStateFile="Random"
CCEinFile="${Directory}/DiaFullP1_15N_exp.json"

## Variables ##
rBathOpt="370"
rDipOpt="330"
B0Opt="292"
OrderOpt="2"
NkOpt=""

## Fixed parameters ## 
OrderFix="2"
PulseFix="1"
deltaTFix="0.001" # 0.3ms = 300us
nStepFix="300"

B0Fix="292"
rBathFix="270"
rDipFix="230"
rDsrdrFix=""
alphaFix="-1"
betaFix="0"

# clustering algo
ClusAlgo="0"
addClus="0"
NkFix="[0,0,0]"

# Hamiltonian
HFOpt=0
HFFile=0 
HFCutoff=0
QuadOpt=0

# JOB
JOBNAME="CCE2e2n_DiaP1_10ppm_"
OutFileDir="./rawdata/"
OutFileHead="CCE2e2n_DiaP1_10ppm_"
OutFileTail=""

