#!/bin/sh
Method="CCE"

Directory="/home/huijin/cal/bath/5.DiaExspins/${PMdefect}"

DefectFile="${Directory}/${PMdefect}bath_12ppm/bath_Dia${PMdefect}_12ppm_Defect"
BathFile="${Directory}/${PMdefect}bath_12ppm/bath_Dia${PMdefect}_12ppm_"
GyroFile="${Directory}/${PMdefect}bath_gyro"
AvaaxFile="Random"
StateFile="Random"
ExStateFile="Random"
CCEinFile="${Directory}/${ccejson}"

## Variables ##
rBathOpt="370"
rDipOpt="330"
B0Opt="${B0Largest}"
OrderOpt="2"
NkOpt=""

## Fixed parameters ## 
OrderFix="2"
PulseFix="1"
deltaTFix="0.0005" # 0.15ms = 150us
nStepFix="300"

B0Fix="${B0Largest}"
rBathFix="250"
rDipFix="200"
rDsrdrFix=""
alphaFix="-1"
betaFix="0"

# clustering algo
ClusAlgo="0"
addClus="0"
NkFix="[0,0,0]"

# Hamiltonian
HFOpt=0
HFFile=0 
HFCutoff=0
QuadOpt=0

# JOB
JOBNAME="CCE2e2n_Dia${PMdefect}_12ppm_"
OutFileDir="./rawdata/"
OutFileHead="CCE2e2n_Dia${PMdefect}_12ppm_"
OutFileTail=""

