#!/bin/sh
Method="CCE"

Directory="/home/huijin/cal/bath/5.DiaExspins/${PMdefect}"

DefectFile="${Directory}/${PMdefect}bath_50ppm/bath_Dia${PMdefect}_50ppm_Defect"
BathFile="${Directory}/${PMdefect}bath_50ppm/bath_Dia${PMdefect}_50ppm_"
GyroFile="${Directory}/${PMdefect}_gyro"
AvaaxFile="Random"
StateFile="Random"
ExStateFile="Random"
CCEinFile="${Directory}/${ccejson}"

## Variables ##
rBathOpt="240"
rDipOpt="220"
B0Opt="${B0Largest}"
OrderOpt="2"
NkOpt=""

## Fixed parameters ## 
OrderFix="2"
PulseFix="1"
deltaTFix="0.0002" # 0.06ms = 60us
nStepFix="300"

B0Fix="${B0Largest}"
rBathFix="140"
rDipFix="120"
rDsrdrFix=""
alphaFix="-1"
betaFix="0"

# clustering algo
ClusAlgo="0"
addClus="0"
NkFix="[0,0,0]"

# Hamiltonian
HFOpt=0
HFFile=0 
HFCutoff=0
QuadOpt=0

# JOB
JOBNAME="CCE2e2n_Dia${PMdefect}_50ppm_"
OutFileDir="./rawdata/"
OutFileHead="CCE2e2n_Dia${PMdefect}_50ppm_"
OutFileTail=""

