#!/bin/sh

ConcList=( 1 5 10 50 100 )

for (( i=0; i<${#ConcList[@]}; i++)) 
do
    SourceFileName="${ConcList[i]}ppm"
    SourceFileDir="/home/huijin/scrp/optCCE/P1BathConcAnisA.2"
    export SourceFileDir;
    export SourceFileName;

    ./domkjobs RM
    ./domkjobs MKE 
#    ./domkjobs RunS 
#    ./domkjobs DS 
#    ./domkjobs DSA 

done 
