#!/bin/sh


System="DiaP1"
spin="14N"

CCEinFile="DiaP1detun_${spin}_exp.json"
CalModel="CCE2"
#enJTEOpt="0"

ConcList=(   1ppm   2ppm   3ppm   4ppm   5ppm   7ppm  10ppm  20ppm  30ppm  40ppm  50ppm  70ppm  100ppm ) 
rBathList=(  850 600 530 520 550 410 370 320 310 280 240 210 160 )
rDipList=(   620 500 470 440 410 370 330 290 270 240 220 200 130 )
#rDsrdrList=( 400 300 250 200 200 200 200 160 150 150 150 150 100 )
deltatList=( '0.01'  '0.003'  '0.003'  '0.002'  '0.001'  '0.0007' '0.0005' '0.0004' '0.0003' '0.0003' '0.0002' '0.0002' '0.0001' )

for (( i=0; i<${#ConcList[@]}; i++))
do

fopt="${ConcList[i]}"

cat << EOF > ${fopt}
#!/bin/sh

Method="CCE"

Directory="/home/huijin/tutorial/Diamond_NV_P1Bath/bath"

DefectFile="\${Directory}/${spin}_${ConcList[i]}/bath_${System}_${ConcList[i]}_Defect"
BathFile="\${Directory}/${spin}_${ConcList[i]}/bath_${System}_${ConcList[i]}_"
GyroFile="\${Directory}/${System}_gyro"
AvaaxFile="Random"
StateFile="Random"
ExStateFile="Random"
CCEinFile="\${Directory}/${CCEinFile}"

## Variables ##
rBathOpt="${rBathList[i]}"
rDipOpt="${rDipList[i]}"
B0Opt="500"
OrderOpt="2"
NkOpt=""

## Fixed parameters ## 
OrderFix="2"
PulseFix="1"
deltaTFix="${deltatList[i]}"
nStepFix="300"

B0Fix="500"
rBathFix="${rBathList[i]}"
rDipFix="${rDipList[i]}"
alphaFix="-1"
betaFix="0"

# clustering algo
ClusAlgo="0"
addClus="0"
NkFix="[0,0,0]"

# Hamiltonian
HFOpt=0
HFFile=0 
HFCutoff=0
QuadOpt=0

# JOB
JOBNAME="${CalModel}_${System}_${ConcList[i]}_"
OutFileDir="./rawdata/"
OutFileHead="${CalModel}_${System}_${ConcList[i]}_"
OutFileTail=""

EOF
################################################################
done

