#!/bin/sh

module purge 
module load icc18 icc18.impi fftw mkl2018

#PwdDir="`pwd`"
#
#cd ../../../../
#
#    make clean
#    make -j$(nproc)
#
#cd "${PwdDir}" 

code="../../../../bin/main.out"
ccein="./cce.json"

process=20

mpirun -n ${process} ${code} -f ${ccein} -v -I "./../../CCE_Reprod/Bath_Data/1.single_data/bath_DiaP1_1ppm_1" > process
#${code} -f ${ccein} -v > process
