#!/bin/sh

cd ../../../

    make

cd ./example/code_verification/CPMG/

code="../../../bin/main.out"
ccein="./cce.json"

process=1

mpirun -np ${process} ${code} -f ${ccein} > process


cat ./process