#!/bin/sh
#SBATCH -J CCE2_DiaP1_100ppm_Order_2
#SBATCH -p 24core
#SBATCH --nodes=8
#SBATCH --ntasks-per-node=24
#SBATCH --cpus-per-task=1
#SBATCH --out outfile
#SBATCH --time=48:00:00
#SBATCH --qos=medium
#SBATCH --mem-per-cpu=5300

module purge 
module load 22.2/icc-22.2 22.2/fftw-3.3.10 22.2/gsl-2.7.1 

export LD_LIBRARY_PATH=/home/CQML/lib/gsl-2.7.1/lib:$LD_LIBRARY_PATH

export OMP_NUM_THREADS=$SLURM_CPUS_PER_TASK
NTASKS=$(($SLURM_NTASKS_PER_NODE * $SLURM_JOB_NUM_NODES))

echo "NTASKS =" $NTASKS
echo "NUM_NODES = " $SLURM_JOB_NUM_NODES
env | grep SLURM

node_process=$NTASKS

#############################################
# Main Paramaters

#bath number

s="$SLURM_ARRAY_TASK_ID"
cista="${s}"
ciend=$(( ${s} + 50 - 1  ))

sista="1"
siend="50"
Nstate=$(( ${siend} - ${sista} + 1 ))

configures=$(seq ${cista} 1 ${ciend})
states=$(seq ${sista} 1 ${siend})


#option input
CodePath="/home/huijin/git/CCEX/bin/main.out"

# inputfiles
mkdir "./rawdata/"
option_input="./ccein.json"
BathFile="/home/huijin/tutorial/Diamond_NV_P1Bath/bath/14N_100ppm/bath_DiaP1_100ppm_"
AvaaxFile="Random"
StateFile="Random"
ExStateFile="Random"

# outfiles
outFile="./rawdata/CCE2_DiaP1_100ppm_Order_2_"

#time checking
startTime=$(date +%s.%N)
startTime_string=`date`
#############################################################################
#about CCE2 calculation 

for m in $configures
do
   	 mpirun -n ${node_process} ${CodePath} -f ${option_input} -I "${BathFile}${m}" -a "${AvaaxFile}${m}" -s "${StateFile}" -S "${ExStateFile}" -o "${outFile}${m}" -N "$Nstate" > "Process_${m}"

done

#############################################################################$
endTime=$(date +%s.%N)
endTime_string=`date`

elapsed=`echo "($endTime-$startTime)" |bc`
htime=`echo "$elapsed/3600"|bc`
mtime=`echo "($elapsed/60)-($htime*60)"|bc`
stime=`echo "$elapsed-(($elapsed/60)*60)"|bc`
echo "Start time : $startTime_string"
echo "End time   : $endTime_string"
echo "Total time : ${htime}H ${mtime}M ${stime}S"

