#!/bin/sh

module purge 
module load  intel-23.2/icc-23.2  intel-23.2/gsl-2.8  intel-23.2/eigen-3.4.0

node_process=20 #$NTASKS

#############################################
# Main Paramaters

varDir="0G"

#bath number
cista="1"
ciend="1"

sista="1"
siend="1"

configures="$(seq -s ' ' ${cista} 1 ${ciend})"
states="$(seq -s ' ' ${sista} 1 ${siend})"

Nstate=0 #$(( ${siend} - ${sista} + 1 ))

#option input
CodePath="$(git rev-parse --show-toplevel)/bin/main.out"

# inputfiles
mkdir "./rawdata/"
option_input="./ccein_v2.js"
BathFile="$(git rev-parse --show-toplevel)/example/Diamond_NV_P1Bath/bath/14N_10ppm/bath_DiaP1_10ppm_"
AvaaxFile="Random"
StateFile="Random"
ExStateFile="Random"

# outfiles
outFile="./rawdata/v2_gCCE2_DiaP1_10ppm_B0_${varDir}_"

#time checking
startTime=$(date +%s.%N)
startTime_string=`date`
#############################################################################
#about CCE2 calculation 

for m in $configures
do
   	 mpirun -n ${node_process} ${CodePath} -f ${option_input} -I "${BathFile}${m}" -a "${AvaaxFile}${m}" -s "${StateFile}" -S "${ExStateFile}" -o "${outFile}${m}" -N "$Nstate" > "Process_${m}"

done


#############################################################################$
endTime=$(date +%s.%N)
endTime_string=`date`

elapsed=`echo "($endTime-$startTime)" |bc`
htime=`echo "$elapsed/3600"|bc`
mtime=`echo "($elapsed/60)-($htime*60)"|bc`
stime=`echo "$elapsed-(($elapsed/60)*60)"|bc`
echo "Start time : $startTime_string"
echo "End time   : $endTime_string"
echo "Total time : ${htime}H ${mtime}M ${stime}S"
#############################################

cd ..

