#!/bin/sh

tool="VASP"
fposcar="./CONTCAR"
dfname="ele"
foutcar="./OUTCAR"
ignoreatm="C"

python ./../../main.py ${tool} ${fposcar} ${dfname} --A ${foutcar} --Q ${foutcar} --ignoreatm ${ignoreatm} --version v2 --fidentify True --rangeformat vertex

################################################################################
<< END

    NOTE! When you have "a atom" at the electron spin site, 
          Because "Actual defect is a electron spin rather than the atom at the electron spin site",
          You MUST add "electron spin" position in your POSCAR/CONTCAR file by hand.

    1) Check POSCAR
        (1) add "ele" (which is electron spin) in the atomic species line  
        (2) add "1" in the right below atomic species line  

            example) 
            B   N   C  B     =>  B   N   C  B  ele   
            55  57  1  3     =>  55  57  1  3   1  

        (3) add the virtual atomic position of "ele" at the last line of POSCAR
            the atomic position should be the same to the position of defect

            example)
            C 0.5 0.5 0.5    =>  C   0.5 0.5 0.5 (Same to ele)
            B 0.4 0.4 0.4    =>  B   0.4 0.4 0.4
            B 0.3 0.3 0.3    =>  B   0.3 0.3 0.3
            B 0.2 0.2 0.2    =>  B   0.2 0.2 0.2
                                ele  0.5 0.5 0.5 (Same to C)

    2) Run AQTensor reader
        (1) dfname (which is defect name) should be "ele"
        (2) use "--ignoreatm" option, and put the on-site defect atom's name after the option
            
            example)
            dfname=ele
            --ignoreatm "C" 
 
END
################################################################################
