#!/bin/sh

mv ./Convert_2_POSCAR_form_bath_hBN_VB_* bathtest/
rm bath_hBN_VB_* -rf

stlist="flat g90 g91 g92 g93 g94 g95 g96 g97 g98 g99"
stlist=" t101 t102 t103 t104 t105 t106 t107 t108 t109 t110 t111 t112 t113 t114 t115 "

for i in $stlist 
do

mkPoscar.py ./bathtest/Convert_2_POSCAR_form_bath_hBN_VB_${i}_1 ./bathtest/POSCAR_${i}

done
