#!/bin/sh

stlist=" t101 t102 t103 t104 t105 t106 t107 t108 t109 t110 t111 t112 t113 t114 t115 "

path="/home/huijin/cal/vasp/14_hBN_tStrain{orth}/results/bathsrc"

for st in $stlist
do

f_flat="${path}/${st}/POSCAR_${st}_pure_rlx_mod"
f_defect="${path}/${st}/POSCAR_${st}_VB_S1_rlx_mod_vb"
f_probability="./prob_hBN"
bathsize="80"
#bathsize="50"
name_impurity="VB" 
name_vacancy="NONE"
nummin=1
nummax=50
#nummax=1
opt_2d="2d"

mkdir ${st}

fout="./${st}/bath_hBN_VB_${st}"
#fout="bath_hBN_VB_${st}"

for ista in $(seq ${nummin} 1 ${nummax})
do
iend=$ista

~/scrp/pyFunction/13.mkBathConfig/BathGenerator_insert.py ${f_flat} ${f_defect} ${f_probability} ${bathsize} ${name_impurity} ${name_vacancy} ${fout} ${ista} ${iend} ${opt_2d}

done

mv "${fout}_Defect" "${fout}_Defect_info"
head -n 2 "${fout}_Defect_info" | tail -n 1 > ${fout}_Defect

done


