#!/bin/sh

stlist=g92 #"flat  g90  g91  g92  g93  g94  g95  g96  g97  g98  g99"

for st in $stlist
do

/home/huijin/cal/vasp/10_hBN_gStrain{hsym}/results_20A/bathsrc
f_flat="/home/huijin/cal/vasp/10_hBN_gStrain{hsym}/results_20A/bathsrc/flat/POSCAR_flat_pure_rlx_mod"
#f_defect="/home/huijin/scratch/hBN/20A_highsym/results_20A/bathsrc/${st}/POSCAR_${st}_VB_S1_rlx_mod_vb_mvatoms" 
f_defect="/home/huijin/cal/vasp/10_hBN_gStrain{hsym}/results_20A/bathsrc/${st}/POSCAR_${st}_VB_S1_rlx_mod_vb"
f_curved="/home/huijin/cal/vasp/10_hBN_gStrain{hsym}/results_20A/bathsrc/${st}/POSCAR_${st}_pure_rlx_mod" 
f_probability="./prob_hBN"
bathsize="80"
name_impurity="VB" 
name_vacancy="NONE"
nummin=9
nummax=9
opt_2d="2d"

mkdir ${st}

fout="./${st}/bath_hBN_VB_${st}"
#fout="bath_hBN_VB_${st}"

for ista in $(seq ${nummin} 1 ${nummax})
do
iend=$ista

if [ ${st} == 'flat' ];then
	/home/huijin/scrp/pyFunction/13.mkBathConfig/BathGenerator_insert.py ${f_flat} ${f_defect} ${f_probability} ${bathsize} ${name_impurity} ${name_vacancy} ${fout} ${ista} ${iend} ${opt_2d}
else
	/home/huijin/scrp/pyFunction/13.mkBathConfig/BathGenerator_curve_insert.py ${f_flat} ${f_defect} ${f_curved} ${f_probability} ${bathsize} ${name_impurity} ${name_vacancy} ${fout} ${ista} ${iend} ${opt_2d}
fi
done

mv "${fout}_Defect" "${fout}_Defect_info"
head -n 2 "${fout}_Defect_info" | tail -n 1 > ${fout}_Defect

done


