#!/bin/sh

stlist=" g90  g91  g92  g93  g94  g95  g96  g97  g98  g99 flat t101 t102 t103 t104 t105 t106 t107 t108 t109 t110"

wkdirS="/home/huijin/cal/vasp/200_hBNAQD{Summary}/"

for i in ${stlist}
do
    
	fout_Afile="${wkdirS}/${i}/HSE_ATensor_${i}_VB_S1_CellPBE"
	fout_Qfile="${wkdirS}/${i}/HSE_QTensor_${i}_VB_S1_CellPBE"
	fout_Dfile="${wkdirS}/${i}/PBEh2h_DTensor_${i}_VB_S1"

	cp ${fout_Afile} "./${i}/" 
	cp ${fout_Qfile} "./${i}/"
	cp ${fout_Dfile} "./${i}/"

done

