#!/bin/sh

#stlist="flat  g90  g91  g92  g93  g94  g95  g96  g97  g98  g99"
#wkdirS="/home/huijin/scratch/hBN/20A_highsym/results_20A/spinHamil/"
#wkdirO="/home/huijin/scratch/hBN/20A_highsym_orth2hexa/results_20A/outcars/"

#stlist=" t101 t102 t103 t104 t105 t106 t107 t108 t109 t110 t111 t112 t113 t114 t115 "
#wkdirS="/home/huijin/cal/vasp/14_hBN_tStrain{orth}/results/spinHamil/"
#wkdirO="/home/huijin/cal/vasp/14_hBN_tStrain{orth}/results/outcars/"


# A tensor, Q tensor from hBN orthrhombic cell

for i in ${stlist}
do

	fout_Afile="${wkdirS}/hBN_VB_${i}_ATensor"
	fout_Qfile="${wkdirS}/hBN_VB_${i}_QTensor"
	out="${wkdirS}/hBN_VB_${i}_mkAQ.out"

	cp ${fout_Afile} "${i}/hBN_VB_${i}_ATensor" 
	cp ${fout_Qfile} "${i}/hBN_VB_${i}_QTensor"
	cp ${out}        "${i}/hBN_VB_${i}_mkAQ.out"

done

# D tensor from hBN orth2hexa cell

for i in ${stlist}
do

	foutcar="${wkdirO}/${i}_VB_S1"
	python zfs_extractor.py ${foutcar} ./${i}/hBN_VB_${i}_DTensor

done
