#!/bin/sh

stlist="flat  g90  g91  g92  g93  g94  g95  g96  g97  g98  g99 t101 t102 t103 t104 t105 t106 t107 t108 t109 t110"
for i in $stlist
do
    #cp "/home/huijin/cal/vasp/19_hBN_fgStrain{orth,HSE}/results/spHamil_v2/hBN_VB_${i}_ATensor_HSE_CellPBE" "${i}/"
    #cp "/home/huijin/cal/vasp/19_hBN_fgStrain{orth,HSE}/results/spHamil_v2/hBN_VB_${i}_QTensor_HSE_CellPBE" "${i}/"
    #cp "/home/huijin/cal/vasp/19_hBN_fgStrain{orth,HSE}/results/spHamil_v2/hBN_VB_${i}_mkAQ.out" "${i}/hBN_VB_${i}_mkAQ_HSE_CellPBE.out"
	#mv "${i}/hBN_VB_${i}_ATensor"  "${i}/hBN_VB_${i}_ATensor_PBE" 
	#mv "${i}/hBN_VB_${i}_QTensor"  "${i}/hBN_VB_${i}_QTensor_PBE"
	#mv "${i}/hBN_VB_${i}_DTensor"  "${i}/hBN_VB_${i}_DTensor_PBE"
	#mv "${i}/hBN_VB_${i}_mkAQ.out" "${i}/hBN_VB_${i}_mkAQ_PBE.out"
	#mv "${i}/hBN_VB_${i}_QTensor__PBE_ADDCORE"  "${i}/hBN_VB_${i}_QTensor_PBE_ADDCORE"
    mkdir bathsummary/${i}
    cp ${i}/bath_hBN_VB_${i}_1      bathsummary/${i}/
    cp ${i}/bath_hBN_VB_${i}_2      bathsummary/${i}/
    cp ${i}/bath_hBN_VB_${i}_3      bathsummary/${i}/
    cp ${i}/bath_hBN_VB_${i}_4      bathsummary/${i}/
    cp ${i}/bath_hBN_VB_${i}_5      bathsummary/${i}/
    cp ${i}/bath_hBN_VB_${i}_6      bathsummary/${i}/
    cp ${i}/bath_hBN_VB_${i}_7      bathsummary/${i}/
    cp ${i}/bath_hBN_VB_${i}_8      bathsummary/${i}/
    cp ${i}/bath_hBN_VB_${i}_9      bathsummary/${i}/
    cp ${i}/bath_hBN_VB_${i}_10     bathsummary/${i}/
    cp ${i}/bath_hBN_VB_${i}_11     bathsummary/${i}/
    cp ${i}/bath_hBN_VB_${i}_12     bathsummary/${i}/
    cp ${i}/bath_hBN_VB_${i}_13     bathsummary/${i}/
    cp ${i}/bath_hBN_VB_${i}_14     bathsummary/${i}/
    cp ${i}/bath_hBN_VB_${i}_15     bathsummary/${i}/
    cp ${i}/bath_hBN_VB_${i}_16     bathsummary/${i}/
    cp ${i}/bath_hBN_VB_${i}_17     bathsummary/${i}/
    cp ${i}/bath_hBN_VB_${i}_18     bathsummary/${i}/
    cp ${i}/bath_hBN_VB_${i}_19     bathsummary/${i}/
    cp ${i}/bath_hBN_VB_${i}_20     bathsummary/${i}/
    cp ${i}/bath_hBN_VB_${i}_Defect     bathsummary/${i}/
done   
