#!/bin/sh

module purge 
module load  intel-23.2/icc-23.2  intel-23.2/gsl-2.8  intel-23.2/eigen-3.4.0
export LD_LIBRARY_PATH=/home/CQML/lib/gsl-2.7.1/lib:$LD_LIBRARY_PATH

node_process=20

PwdDir="`pwd`"

cd "/home/huijin/scrp/CCE_Code/17.5.5.version11_pm_apprx/"

./do_compile

cd $PwdDir

#option input
CodePath="/home/huijin/scrp/CCE_Code/17.5.5.version11_pm_apprx/CCEXv12.out"

# inputfiles
option_input="./cce.in"

# outfiles
outFile="./CCE2_DiaP1_1ppm_1"

#time checking
startTime=$(date +%s.%N)
startTime_string=`date`
#############################################################################
#about CCE2 calculation 

mpirun -n ${node_process} ${CodePath} -f ${option_input} -o ${outFile} -v > "Process_1"

#${CodePath} -f ${option_input} -o ${outFile} -v > "Process_1"


#############################################################################$
endTime=$(date +%s.%N)
endTime_string=`date`

elapsed=`echo "($endTime-$startTime)" |bc`
htime=`echo "$elapsed/3600"|bc`
mtime=`echo "($elapsed/60)-($htime*60)"|bc`
stime=`echo "$elapsed-(($elapsed/60)*60)"|bc`
echo "Start time : $startTime_string"
echo "End time   : $endTime_string"
echo "Total time : ${htime}H ${mtime}M ${stime}S"
#############################################
