#!/bin/sh

unit=""
VariableName="Order"
varOpt="2"

##############################################################
cista=1
ciend=50
configs="$(seq ${cista} 1 ${ciend})"

sista=1
siend=50
states="$(seq ${sista} 1 ${siend})"

fittingCode="/home/huijin/git/CoherenceAnalyzer/run.py"

CdMkDir ./summary/
CdMkDir ./summary/${VariableName}/
CdMkDir ./summary/${VariableName}/ErrorCorr
CdMkDir ./summary/${VariableName}/TimeEnsemble
CdMkDir ./summary/${VariableName}/SpatialEnsemble
##############################################################
for var in ${varOpt} 
do
    
    datadirectory="./${VariableName}/${var}${unit}"
    rawdatadirectory="${datadirectory}/rawdata"
    rawdatahead="CCE2e2n_DiaP1_100ppm_${VariableName}_${var}${unit}"

    ###################################################
    # Convert Name
	variable_name_1="CONF"
	variable_values_1="${configs}"
	variable_name_2="STATE"
	variable_values_2="${states}"

	data_directory="./${VariableName}/${var}${unit}/rawdata/"
	data_filename_format="${rawdatahead}_${variable_name_1}_state${variable_name_2}_wiDiv"
    data_filename_format_ref="${rawdatahead}_${variable_name_1}_state${variable_name_2}_noDiv"

	result_directory="./summary/${VariableName}/SpatialEnsemble/"
	result="${result_directory}${rawdatahead}_sE"

	# Ensemble average option   : -ea
	# Unit conversion           : -uc [unit] (use default unit (ms))
	# Nan to num                : -ntn
	# Error correction			: -err
	python ${fittingCode} -d "${data_directory}" -fi "${data_filename_format}" -vn ${variable_name_1} ${variable_name_2} -v ${variable_values_1} -v ${variable_values_2} -uc "ms" -ea -ntn -fo "${result}" -pl -fit -err_d "${data_directory}" -err_fi "${data_filename_format_ref}" -err

done

##################################################################
# Intensity plot for variable (You can turn off by hand)

variable_name="VAR"
result_directory="./summary/${VariableName}/SpatialEnsemble/"

# Convergence number
ncnf=$(( ${ciend} - ${cista} + 1  ))
nstat=$(( ${siend} - ${sista} + 1  ))
convnum=$(( ${ncnf} * ${nstat} ))

rawdatahead="CCE2e2n_DiaP1_100ppm_${VariableName}_${variable_name}${unit}"
result_filename="${rawdatahead}_sE_conv${convnum}"

# Intensity plot
# python ${fittingCode} -d "${result_directory}" -fi "${result_filename}" -vn ${variable_name} -v ${varOpt} -uc "us" -ntn -fo "${result_directory}${result_filename}" -pl_i 

# fitting parameters
python ${fittingCode} -d "${result_directory}" -fi "${result_filename}" -vn ${variable_name} -v ${varOpt} -uc "us" -ntn -fo "${result_directory}${result_filename}" -fit_w -pl_T -pl_p
##################################################################


