#!/bin/sh

module purge 
module load 22.2/icc-22.2 22.2/fftw-3.3.10 22.2/gsl-2.7.1 

node_process=1

#############################################
# Main Paramaters

#bath number

s=1
cista="${s}"
ciend=$(( ${s} + 1 - 1  ))

sista="1"
siend="1"
Nstate=$(( ${siend} - ${sista} + 1 ))

configures=$(seq ${cista} 1 ${ciend})
states=$(seq ${sista} 1 ${siend})


#option input
CodePath="/home/huijin/git/CCEX/bin/main.out"

# inputfiles
mkdir "./rawdata/"
option_input="./ccein.json"
BathFile="/home/huijin/tutorial/Diamond_NV_P1Bath/bath/14N_1ppm/bath_DiaP1_1ppm_"
AvaaxFile="Random"
StateFile="Random"
ExStateFile="Random"

# outfiles
outFile="./rawdata/CCE4_DiaP1_1ppm_Order_4_"

#time checking
startTime=$(date +%s.%N)
startTime_string=`date`
#############################################################################
#about CCE2 calculation 

for m in $configures
do
   	 mpirun -n ${node_process} ${CodePath} -f ${option_input} -I "${BathFile}${m}" -a "${AvaaxFile}${m}" -s "${StateFile}" -S "${ExStateFile}" -o "${outFile}${m}" -N "$Nstate" > "Process_${m}"

done

#############################################################################$
endTime=$(date +%s.%N)
endTime_string=`date`

elapsed=`echo "($endTime-$startTime)" |bc`
htime=`echo "$elapsed/3600"|bc`
mtime=`echo "($elapsed/60)-($htime*60)"|bc`
stime=`echo "$elapsed-(($elapsed/60)*60)"|bc`
echo "Start time : $startTime_string"
echo "End time   : $endTime_string"
echo "Total time : ${htime}H ${mtime}M ${stime}S"

