#!/bin/sh
Method="CCE"

Directory="/home/huijin/cal/bath/5.DiaExspins/NVHn"

DefectFile="${Directory}/NVHnbath_10ppm/bath_DiaNVHn_10ppm_Defect"
BathFile="${Directory}/NVHnbath_10ppm/bath_DiaNVHn_10ppm_"
GyroFile="${Directory}/NVHn_gyro"
AvaaxFile="Random"
StateFile="Random"
ExStateFile="Random"
CCEinFile="${Directory}/cce_15N_ortho1_avg.json"

## Variables ##
rBathOpt="370"
rDipOpt="330"
B0Opt="292"
OrderOpt="2"
NkOpt=""

## Fixed parameters ## 
OrderFix="2"
PulseFix="1"
deltaTFix="0.001" # 0.3ms = 300us
nStepFix="300"

B0Fix="292"
rBathFix="370"
rDipFix="330"
rDsrdrFix=""
alphaFix="-1"
betaFix="0"

# clustering algo
ClusAlgo="0"
addClus="0"
NkFix="[0,0,0]"

# Hamiltonian
HFOpt=0
HFFile=0 
HFCutoff=0
QuadOpt=0

# JOB
JOBNAME="CCE2e2n_DiaNVHn_10ppm_"
OutFileDir="./rawdata/"
OutFileHead="CCE2e2n_DiaNVHn_10ppm_"
OutFileTail=""

