#!/bin/sh
Method="CCE"

Directory="/home/huijin/cal/bath/5.DiaExspins/P1"

DefectFile="${Directory}/P1bath_50ppm/bath_DiaP1_50ppm_Defect"
BathFile="${Directory}/P1bath_50ppm/bath_DiaP1_50ppm_"
GyroFile="${Directory}/P1_gyro"
AvaaxFile="Random"
StateFile="Random"
ExStateFile="Random"
CCEinFile="${Directory}/DiaFullP1_14N_exp.json"

## Variables ##
rBathOpt="240"
rDipOpt="220"
B0Opt="325.7"
OrderOpt="2"
NkOpt=""

## Fixed parameters ## 
OrderFix="2"
PulseFix="1"
deltaTFix="0.0002" # 0.06ms = 60us
nStepFix="300"

B0Fix="325.7"
rBathFix="240"
rDipFix="220"
rDsrdrFix=""
alphaFix="-1"
betaFix="0"

# clustering algo
ClusAlgo="0"
addClus="0"
NkFix="[0,0,0]"

# Hamiltonian
HFOpt=0
HFFile=0 
HFCutoff=0
QuadOpt=0

# JOB
JOBNAME="CCE2e2n_DiaP1_50ppm_"
OutFileDir="./rawdata/"
OutFileHead="CCE2e2n_DiaP1_50ppm_"
OutFileTail=""

