#!/bin/sh

if [ $# == 2 ]; then

    echoio="$2"
    
    if [ ! -d "$1" ]; then
    	mkdir "$1"
    else
    :
    fi
    
    if [ ${echoio} == "on" ];then
        echo "$1"
    fi

elif [ $# == 1 ]; then

    if [ ! -d "$1" ]; then
    	mkdir "$1"
    else
    :
    fi
    
    echo "$1"

fi
