#!/bin/sh
#SBATCH -J Diamond_NV_natab
#SBATCH -p 24core
#SBATCH --nodes=4
#SBATCH --ntasks-per-node=24
#SBATCH --cpus-per-task=1
#SBATCH --out outfile
#SBATCH --time=72:00:00
#SBATCH --qos=small-2
#SBATCH --mem-per-cpu=5300
#SBATCH --exclusive

module load anaconda3-2024.10-1

Destination=./../

HostMat="Diamond"
SpinQubit="NV"
SpinBath="natab"

CodePath="$(git rev-parse --show-toplevel)/example/z.BathGenerator/BathGenerator.py"

############################################################
# Generate bath configuration 
size=150
prob=./prob_natab
Defect=V
inputfile=./POSCAR_pure
insert=./POSCAR_NV

SpatialConfig=${Destination}bath_${HostMat}_${SpinQubit}_${SpinBath}

for i in $(seq 1 1 20)
do

SpinQubitPos="0.5 0.5 0.5" 

${CodePath} -o ${SpatialConfig}_${i} -i $inputfile -I $insert -p $prob --size $size --Defect $Defect --Defect_center ${SpinQubitPos} > ${Destination}Process_${i} &

done
wait

############################################################
# Change file name
for i in $(seq 1 1 20)
do

mv ${SpatialConfig}_${i}_defect  ${SpatialConfig}_defect

done
############################################################
